
[Variables]
;;Version of Skin
Version=1.0
;;Alpha Background DVDLogo
alpha=1
;;Background 
FGType=Blur
;;Logo Type
LGType=2
;;Logo Colors
LCLeft=0276E3
LCRight=00C2A8
LCBottom=FF5254
LCTop=F7C600
;;Shortcuts | Default  Lock = ALT L  ; Unlock = ALT U
LockHK=ALT L
UnLockHK=ALT U
;;IdleTime | Default 120
sleepA=120
;;Speed | Default : 2
speedL=2
;; Width and height of the logo 
;; It's very important to have the same values as the original image of the logo 
;; Default   w = 425; h = 216
wLogo = 425  
hLogo = 216



